# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

dump_dir: /mnt/nfs/home/gmi/training_output
name: "debug"
steps: 1000
probe_freq: 100
seed: 777
optim:
    lr: 3e-4
    warmup: 2000
    lr_min_ratio: 0.000001
    clip: 10.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    num_nodes: 1
    gpus_per_node: 8
    tp_size: 2

model:
    dim: 1024
    n_layers: 8
    n_heads: 8

data:
    root_dir: /mnt/nfs/home/gmi/hf_data/HuggingFaceFW
    sources:
        # dclm_baseline_1.0: 1.0
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 32
    prefetch_size: 64
    seq_len: 2048
    n_views: 2
    load_async: true
    tokenizer:
        name: bytes
        path: /mnt/nfs/home/gmi/hf_models/meta-llama/Llama-3.2-3B

profiling:
    run: true

checkpoint:
    dump:
        every: 100
        keep: 1
    eval:
        every: 100
        keep: 1

logging:
    freq: 10

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
        temperature: 1.0
        top_p: 0.95
    harness:
        tasks:
            - hellaswag
            - piqa
            - task: nq_open
              num_fewshot: 5
    validation:
        max_steps: 100
